### ISSUE TITLE
Link to github.com/apps/MSBuildLogOctokitChecker in README.md 404s

### ISSUE THREAD

**Issue by jcansdale** [justaprogrammer/MSBuildLogOctokitChecker#88]
Has this link changed?

https://github.com/justaprogrammer/MSBuildLogOctokitChecker/blame/master/README.md#L20

**Comment by martincostello** [comment]
Was just about to open an issue myself. Should be: https://github.com/apps/msbuildlog-octokit-checker

**Comment by jcansdale** [comment]
@martincostello thanks, I've submitted a PR to link to that one. 👍

**Comment by StanleyGoldman** [comment]
Derp, thanks guys.
